'use strict';document.addEventListener('DOMContentLoaded',()=>{let darkTheme=createRootColorsObj().darkTheme,lightTheme=createRootColorsObj().lightTheme;function createRootColorsObj(){return{darkTheme:{'--fst_main':'#002137','--snd_main':'#18171c','--text':'#ffffff','--border':'#ffffff','--btn':'#ffffff','--btn-text':'#000000','--btn-hover-background':'#c7d0cc','--link-non-visited':'#c3e4e8','--link-hover':'#c7d0cc',},lightTheme:{'--fst_main':'#fc3','--snd_main':'#FFF973','--text':'#303','--border':'#000029','--btn':'#000029','--btn-text':'#fff','--btn-hover-background':'rgba(0, 0, 41, .9)','--link-non-visited':'#310062','--link-hover':'#aaa',},};}
function changeRootColor(colorObj){for(let CSSVar in colorObj){document.querySelector(':root').style.setProperty(CSSVar,colorObj[CSSVar]);}}
function animateChangingColors(){document.querySelector('body').classList.add('fadeIn','animate__fadeIn');setTimeout(()=>{document.querySelector('body').classList.remove('fadeIn','animate__fadeIn');},1200);}
function changeToLightTheme(){document.querySelector('.changeToLightTheme').addEventListener('click',()=>{changeRootColor(lightTheme);animateChangingColors();document.querySelector('.changeToLightTheme').style.display='none';document.querySelector('.changeToDarkTheme').style.display='inline-block';});}
function changeToDarkTheme(){document.querySelector('.changeToDarkTheme').addEventListener('click',()=>{changeRootColor(darkTheme);animateChangingColors();document.querySelector('.changeToDarkTheme').style.display='none';document.querySelector('.changeToLightTheme').style.display='inline-block';});}
changeToLightTheme();changeToDarkTheme();function getTitles(){let h1=document.querySelector('h1'),h2=document.querySelectorAll('h2'),h3=document.querySelectorAll('h3');return[h1,...h2,...h3];}
function setSpecialCharColors(){return['#f00','#0a0'];}
function colorTitles(titles,color){titles.forEach((item)=>{let a=item.innerText,b=a.slice(0,a.length-3),specialChar=a.charAt(a.length-3),colorElem=`<font color="${color}">${specialChar}</font>`,c=a.slice(a.length-2,a.length+1);item.innerHTML='';item.innerHTML=`${b}${colorElem}${c}`;});}
colorTitles(getTitles(),setSpecialCharColors()[0]);let hamburger=document.querySelector('.hamburger'),menu=document.querySelector('.menu__block'),overlay=document.querySelector('.menu__overlay'),close=document.querySelector('.menu__close');function showOrHideMenu(){menu.classList.toggle('active');overlay.classList.toggle('active');document.body.classList.toggle('noScroll');}
hamburger.addEventListener('click',showOrHideMenu);close.addEventListener('click',showOrHideMenu);overlay.addEventListener('click',showOrHideMenu);document.addEventListener('keydown',(e)=>{if(e.key=='Escape'&&menu.classList.contains('active')){showOrHideMenu();}});let links=document.querySelectorAll('[data-inside=""]');function goToSection(){links.forEach((item)=>{item.addEventListener('click',(e)=>{let id=e.target.getAttribute('href'),section=document.querySelector(id);section.firstElementChild.classList.add('fadeInUp','animate__fadeInUp');setTimeout(()=>{section.firstElementChild.classList.remove('fadeInUp','animate__fadeInUp');},1100);});});}
goToSection();class Validator{constructor(name,email){this.name=name;this.email=email;}
validateName(name){let chars=[...'!@.#$"%^&*()_-?№;:+=/<>|,\'\\'],numbers=[...'0123456789'],arr=[];chars.forEach(i=>{if(name.value.includes(i))arr.push(1);else arr.push(0);});numbers.forEach(i=>{if(name.value.indexOf(i)===-1)arr.push(0);else arr.push(1);});if(arr.some(i=>i==1)||name.value!=''&&name.value.length<2){name.style.border='solid 2px red';name.setAttribute('data-error','');}else{name.style.border='solid 1px var(--border)';name.removeAttribute('data-error');}}
validateEmail(email){let arr=[],position=email.value.indexOf('@'),domains=['gmail','yandex','yahoo','outlook','hotmail','rambler','lenta','autorambler','myrambler','ro','mail','inbox','list','bk'];domains.forEach((item)=>{arr.push(email.value.indexOf(item,position));});if(arr.some(i=>i!==-1)){email.style.border='solid 1px var(--border)';email.removeAttribute('data-error');}else{email.style.border='solid 2px red';email.setAttribute('data-error','');}}}
const validator=new Validator();let nameField=document.querySelector('#name'),emailField=document.querySelector('#email'),offertLink=document.querySelector('.privacy'),offert=document.querySelector('.privacy-overlay'),offertclose=document.querySelector('.close-privacy__btn'),feedbackForm=document.forms.feedback,closeGraceModal=document.querySelector('.modal-thanks .window button'),windowGraceModal=document.querySelector('.modal-thanks');function showOrHideOffert(offertWindow){offertWindow.classList.toggle('active');document.body.classList.toggle('noScroll');}
function showLoadAnimation(){let text=document.querySelector('.label'),animation=document.querySelector('.progress');text.style.display='none';animation.style.display='block';}
function hideLoadAnimation(){let text=document.querySelector('.label'),animation=document.querySelector('.progress');text.style.display='inline';animation.style.display='none';}
function sendForm(form){form.addEventListener('submit',(e)=>{if(nameField.hasAttribute('data-error')||emailField.hasAttribute('.data-error')){e.preventDefault();return false;}else{e.preventDefault();let feedback=new FormData(form),xhr=new XMLHttpRequest(feedback);xhr.open('POST','mailer/smart.php');xhr.send();showLoadAnimation();xhr.addEventListener('load',()=>{hideLoadAnimation();showOrHideGraceModal(windowGraceModal);form.reset();});}});}
function showOrHideGraceModal(gracemodal){gracemodal.classList.toggle('active');document.body.classList.toggle('noScroll');}
nameField.addEventListener('blur',()=>{let nameError=document.querySelector('#nameError');validator.validateName(nameField);if(nameField.hasAttribute('data-error')&&nameField.value.length<=1){nameError.style.display='block';nameError.innerText='Имя не должно быть короче двух символов';}else if(nameField.hasAttribute('data-error')&&nameField.value.length>1){nameError.style.display='block';nameError.innerText='Имя не должно содержать цифры и посторонние символы';}else{nameError.style.display='none';}});emailField.addEventListener('blur',()=>{let emailError=document.querySelector('#emailError');validator.validateEmail(emailField);if(emailField.hasAttribute('data-error')&&emailField.value!=''){emailError.style.display='block';emailError.innerText='Введен недопустимый Email';}else{emailError.style.display='none';}});offertLink.addEventListener('click',()=>showOrHideOffert(offert));offertclose.addEventListener('click',()=>showOrHideOffert(offert));sendForm(feedbackForm);closeGraceModal.addEventListener('click',()=>showOrHideGraceModal(windowGraceModal));});
